name: Build and Deploy Godot HTML5

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: 4.4.1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Godot and templates
        uses: actions/cache@v4
        with:
          path: |
            godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          key: godot-${{ env.GODOT_VERSION }}

      - name: Download Godot
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d godot
          mv godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot/godot
          chmod +x godot/godot

      - name: Download Godot Export Templates
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz -O templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          unzip -q templates.tpz -d templates
          mv templates/templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/

      - name: Build HTML5
        run: |
          mkdir -p build
          ./godot/godot --headless --export-release "Web" build/index.html

      - name: Move build to branch subfolder
        run: |
          mkdir -p deploy/${{ github.ref_name }}
          cp -r build/* deploy/${{ github.ref_name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages-static
          keep_files: true
          
      - name: Create redirect to main
        run: |
          mkdir -p deploy
          cat > deploy/index.html <<'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=./main/">
              <title>Redirecting...</title>
            </head>
            <body>
              <p>Redirecting to <a href="./main/">main</a>...</p>
            </body>
          </html>